experiment:
    name: nomad_100
    metrics: 
      - mean_absolute_error
      - mean_squared_error
      - r2_score
      - mean_absolute_percentage_error

    logging:
        path: src/data_science/results/
        filename: nomad_100

    data:
        path: data/processed/NOMAD
        in_situ_dataset: in_situ_MERIS.csv
        simulation_dataset: simulation_MERIS.csv
        simulation_samples: 100000
        simulation_config: generic
        simulation_target_col: chla 
        in_situ_target_col: chla
        feature_cols:
          - rrs_MER1
          - rrs_MER2
          - rrs_MER3
          - rrs_MER4
          - rrs_MER5
          - rrs_MER6
          - rrs_MER7

        url: https://raw.githubusercontent.com/victorneuteboom/master-thesis-public-data/master/data/NOMAD/NOMAD.zip

    split:
        train_samples: 100

    random:
        seed: 1

plotting:
    figsize_x: 7
    figsize_y: 7
    title_fontsize: 20
    label_fontsize: 14
    tick_fontsize: 14
    legend_fontsize: 14
    cmap: "coolwarm"
    save_fig: True

models:
    auto_sklearn: 
        output: models/autosklearn
        n_jobs: 1
        time_per_task: 1080 #18 minutes 
        total_time: 10800 # 3 hours
        memory_limit: 6144 #6 GB