experiment:
    name: yield_50
    metrics: 
      - mean_absolute_error
      - mean_squared_error
      - r2_score
      - mean_absolute_percentage_error

    logging:
        path: src/data_science/results/
        filename: yield_50

    data:
        path: data/processed/yield
        in_situ_dataset: in_situ_weekly_10m_filtered.csv
        simulation_dataset: PROSAIL_LUT_Sentinel2_100000_winter_wheat.csv
        simulation_samples: 100000
        simulation_config: generic
        simulation_target_col:
          - lai
          - cm
          - cw
        in_situ_target_col: 'Ertr.masse (Nass)(tonne/ha)'

        feature_cols:
        - 'B1'
        - 'B2'
        - 'B3'
        - 'B4'
        - 'B5'
        - 'B6'
        - 'B7'
        - 'B8A'
        - 'B9'
        - 'B11'
        - 'B12'
        - 'solar_zenith'
        - 'observer_zenith'
        - 'relative_azimuth'

        extra_feature_cols:
        - et0
        - cum_rain
        - rain

        url: https://raw.githubusercontent.com/victorneuteboom/master-thesis-public-data/master/data/yield/yield.zip

        n_timesteps: 21

    split:
        train_samples: 50

    random:
        seed: 1

plotting:
    figsize_x: 7
    figsize_y: 7
    title_fontsize: 20
    label_fontsize: 14
    tick_fontsize: 14
    legend_fontsize: 14
    cmap: "coolwarm"
    save_fig: True

models:
    auto_sklearn: 
        output: models/autosklearn
        n_jobs: 1
        time_per_task: 1080 #18 minutes 
        total_time: 10800 # 3 hours
        memory_limit: 6144 #6 GB